### ISSUE TITLE
Release for coq 8.13

### ISSUE THREAD

**Issue by ddemange** [coq-community/atbr#32]
Is there a plan to do a release for coq 8.13? 
The latest release is compiling with a deprecation warning about `Coqlib.find_reference`.
The same issue occurs on the `coq-8.13-compat` branch.

I'm also getting some warnings at link-time. `ld` complains about not finding any directory for Coq IDE -- both on the latest release and the coq-8.13-compat. Should coq-ide be considered as a dependency of `atbr`? 

Thanks!

**Comment by palmskog** [comment]
Releases for Coq 8.13 to 8.17 are done, specifically https://github.com/coq-community/atbr/releases/tag/v8.13.0
