### ISSUE TITLE
Branch for Coq 8.9?

### ISSUE THREAD

**Issue by palmskog** [coq-community/atbr#5]
I'm interested in experimenting with this project using Coq 8.9. However, currently, the `master` branch does not compile with Coq 8.9beta1 or Coq's `v8.9` branch. Any chance for a `v8.9` branch I can target with PRs, or can I just create that branch?

**Comment by tchajed** [comment]
It looks like the v8.8 branch has everything needed for compatibility Coq v8.9 (other than a bunch of warnings), so I went ahead and created [v8.9](https://github.com/coq-community/atbr/tree/v8.9) off of v8.8.

**Comment by palmskog** [comment]
Thanks!
